#!/bin/sh
#
# Взято отсюда: http://habrahabr.ru/blogs/development/111691/
#

mkdir -p bin
mkdir -p obj
mkdir -p obj/Debug
make --directory=./obj/Debug --makefile=../../Makefile build_flags="-g" program_name=../../bin/appDBG
